### ISSUE TITLE
Custom alarm keypad card not showing after HA update to 15.0

### ISSUE THREAD

**Issue by robotsyte** [Dilbert66/esphome-dsckeybus#164]
Hi!

My Custom alarm keypad had worked well until the operating system updated to 15.0. Not it does not show any error messages in editor, but the kaypad is not showing.
Can you help me, what can be the issue?

Thanks!

![Image](https://github.com/user-attachments/assets/ec57dbc7-25dd-492d-85fa-a553f671fa7a)

**Comment by hiltctn** [comment]
Same issue on my end.  

HA 2025.2.5 ( Docker on Synology )

**Comment by Dilbert66** [comment]
Fixed in latest version

**Comment by hiltctn** [comment]
> Fixed in latest version

Hi Alain.  

I updated the alarm-keypad-card.js file to latest.  No change unfortunately.  It renders blank

**Comment by Dilbert66** [comment]
Browser caching issue. Do this:
In the lovelace, resources tab in resources

Add the resource eg /local/irrigation-card.js?v=1 increment the version number if updating an exsting installation
Then just refresh the browser

**Comment by hiltctn** [comment]
I've incremented id=1 to id=2. "Now met with Custom element doesn't exist"  error. 

I updated HA and did a full restart.  Tried a different browser ( Safari ) on a Mac.  So I don't think it's a caching issue ( Chrome has caught me with that before with HA )

![Image](https://github.com/user-attachments/assets/ad520760-0048-435e-803b-c588e639c386)

![Image](https://github.com/user-attachments/assets/21e63669-7544-4257-9e58-922c75fee7f4)

**Comment by hiltctn** [comment]
![Image](https://github.com/user-attachments/assets/c3b862cd-e282-4910-8b87-b991ee7453ec)

**Comment by Dilbert66** [comment]
Honestly, I have no idea why it doesnt work for you. The card is fine here.  Make sure the top of the javascript has this:
```
const LitElement = Object.getPrototypeOf(customElements.get("ha-panel-lovelace"));
const html = LitElement.prototype.html;
const css = LitElement.prototype.css;
```
If not, then your file was not updated.   
Also, make sure you do an f5 on the page where the card is.  If you still get an error  then oopen up the developer console with f12 and see what the error is.

**Comment by robotsyte** [comment]
> Fixed in latest version

Hi, thanks for the fast reaction. It has solve the issue.
Thanks again.

**Comment by Dilbert66** [comment]
Dev was update before master.

**Comment by olddawgpowers** [comment]
In the lovelace.yaml line 115 and 118 error as duplicates

**Comment by Dilbert66** [comment]
I've corrected the example

**Comment by JacoAnnandale** [comment]
Good morning all

I still dont get the custom alarm panel to show.  Did all that was suggested in this thread, but to no avail.  

Have you got any suggestions?
